"""
schemas/decision.py

Deterministic Governance Core (DGC)

Decision Schema

Represents the final governance decision generated by the
Decision Engine after policy evaluation, risk scoring,
and compliance analysis.

This object is intended to be machine-readable.

Human-readable explanations should be generated later by
the AI Advisory Layer.
"""

from datetime import datetime
from enum import Enum
from uuid import uuid4

from pydantic import BaseModel, ConfigDict, Field


#
# Decision Status
#

class DecisionStatus(str, Enum):

    APPROVED = "approved"

    DENIED = "denied"

    REVIEW_REQUIRED = "review_required"

    ESCALATED = "escalated"

    DEFERRED = "deferred"


#
# Action
#

class DecisionAction(str, Enum):

    NONE = "none"

    ALLOW_TOOL = "allow_tool"

    DENY_TOOL = "deny_tool"

    CREATE_JIRA = "create_jira"

    SEND_SLACK = "send_slack"

    SEND_EMAIL = "send_email"

    GENERATE_REPORT = "generate_report"

    BLOCK_DEPLOYMENT = "block_deployment"

    QUARANTINE_RESOURCE = "quarantine_resource"

    REQUIRE_HUMAN_APPROVAL = "require_human_approval"


#
# Decision Object
#

class Decision(BaseModel):

    model_config = ConfigDict(

        extra="forbid",

        validate_assignment=True,

        use_enum_values=True,
    )

    #
    # Identity
    #

    decision_id: str = Field(
        default_factory=lambda: str(uuid4()),
        description="Unique Decision Identifier"
    )

    timestamp: datetime = Field(
        default_factory=datetime.utcnow,
        description="UTC Timestamp"
    )

    #
    # Relationships
    #

    event_id: str = Field(
        description="SecurityEvent that produced this decision."
    )

    correlation_id: str | None = Field(
        default=None,
        description="Workflow correlation identifier."
    )

    #
    # Governance
    #

    status: DecisionStatus

    action: DecisionAction

    #
    # Risk
    #

    risk_score: int = Field(
        ge=0,
        le=100,
        description="Enterprise Risk Score"
    )

    confidence: float = Field(
        ge=0.0,
        le=1.0,
        description="Confidence in deterministic evaluation."
    )

    #
    # Decision Explanation
    #

    rationale: str = Field(
        description="Deterministic explanation for the decision."
    )

    #
    # Policy References
    #

    policy_ids: list[str] = Field(
        default_factory=list,
        description="Policies evaluated during decision."
    )

    framework_mappings: list[str] = Field(
        default_factory=list,
        description="OWASP, NIST, CIS, PCI, etc."
    )

    #
    # Decision Trace
    #

    decision_path: list[str] = Field(
        default_factory=list,
        description="Ordered list of engines/rules evaluated."
    )

    #
    # Human Approval
    #

    approval_required: bool = False

    approved_by: str | None = None

    approved_time: datetime | None = None

    #
    # Additional Metadata
    #

    metadata: dict = Field(
        default_factory=dict
    )
