apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: argocd
data:
  # Default: read-only unless explicitly allowed
  policy.default: role:readonly

  # Optional: make Argo log RBAC decisions (useful in class)
  policy.matchMode: glob

  # RBAC policy rules (Casbin)
  policy.csv: |
    # --- Roles ---
    # readonly role: allow viewing everything
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, projects, get, */*, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, clusters, get, *, allow

    # dev/test operator: can sync and manage apps in dev/test projects only
    p, role:devtest-operator, applications, get, */*, allow
    p, role:devtest-operator, applications, sync, splunk-dev/*, allow
    p, role:devtest-operator, applications, sync, splunk-test/*, allow
    p, role:devtest-operator, applications, update, splunk-dev/*, allow
    p, role:devtest-operator, applications, update, splunk-test/*, allow
    p, role:devtest-operator, applications, action/*, splunk-dev/*, allow
    p, role:devtest-operator, applications, action/*, splunk-test/*, allow

    # explicitly deny touching prod (not strictly required if not granted,
    # but it's a great teaching point)
    p, role:devtest-operator, applications, sync, splunk-prod/*, deny
    p, role:devtest-operator, applications, update, splunk-prod/*, deny
    p, role:devtest-operator, applications, action/*, splunk-prod/*, deny

    # admin: can do anything
    p, role:admin, *, *, *, allow

    # --- Group/User bindings ---
    # Group "students" gets dev/test operator permissions
    g, students, role:devtest-operator

    # Group "admins" gets full admin
    g, admins, role:admin
