FROM python:3.11-slim

RUN apt-get update && apt-get install -y curl apt-transport-https ca-certificates gnupg

RUN curl -LO "https://dl.k8s.io/release/v1.30.0/bin/linux/amd64/kubectl" \
    && install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

WORKDIR /app

COPY agent.py .

RUN pip install google-genai

CMD ["python", "agent.py"]

  # remember dockerfile has no extension
