apiVersion: v1
kind: ServiceAccount

metadata:
  name: guardian-agent
  namespace: ai-governance

  annotations:
    iam.gke.io/gcp-service-account: \
      guardian-agent@PROJECT_ID.iam.gserviceaccount.com
